[[pages]]
path = "pages/1_Home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/2_Cadastro.py"
name = "Cadastro"
icon = "ğŸ“"

[[pages]]
path = "pages/3_CatÃ¡logo.py"
name = "CatÃ¡logo"
icon = "ğŸ“‚"

[[pages]]
path = "pages/4_Analytics.py"
name = "Analytics"
icon = "ğŸ“ˆ"

[[pages]]
path = "pages/5_Chat.py"
name = "Chatbot - IA"
icon = "ğŸ¤–"
